/**
 * CENTRAL TOOL REGISTRY — LESS CREATION
 * Standardized metadata, categories, SEO definitions, and FAQs for all tools.
 * Enables adding new tools seamlessly without rewriting application architecture.
 */

import { ToolDefinition, ToolCategory } from '../types';

export const TOOL_CATEGORIES: { id: ToolCategory; label: string; labelHi: string; icon: string; description: string }[] = [
  { id: 'pdf', label: 'PDF Tools', labelHi: 'पीडीएफ टूल्स', icon: 'FileText', description: 'Merge, split, rotate, convert, and compress PDFs on-device.' },
  { id: 'image', label: 'Image Tools', labelHi: 'इमेज टूल्स', icon: 'Image', description: 'Resize, compress, convert formats, and crop photos in browser.' },
  { id: 'text', label: 'Text Tools', labelHi: 'टेक्स्ट टूल्स', icon: 'Type', description: 'Count words, change case, remove duplicates, and clean text.' },
  { id: 'calculators', label: 'Calculators', labelHi: 'कैलकुलेटर', icon: 'Calculator', description: 'EMI, GST, Age, Percentage, and Unit converters.' },
  { id: 'qr-digital', label: 'QR & Digital', labelHi: 'क्यूआर और डिजिटल', icon: 'QrCode', description: 'QR generator, scanner, passwords, JSON, and Base64 utilities.' },
  { id: 'productivity', label: 'Productivity', labelHi: 'उत्पादकता', icon: 'CheckSquare', description: 'Checklists, scratchpad notes, focus timers, and random pickers.' },
];

export const TOOLS_REGISTRY: ToolDefinition[] = [
  // ===================== A. PDF TOOLS =====================
  {
    id: 'tool-pdf-merge',
    name: 'PDF Merge',
    nameHi: 'पीडीएफ मर्ज',
    slug: 'pdf-merge',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    categoryLabelHi: 'पीडीएफ टूल्स',
    description: 'Combine multiple PDF documents into a single organized file in seconds.',
    descriptionHi: 'कई पीडीएफ फाइलों को एक संगठित फाइल में आसानी से जोड़ें।',
    iconName: 'Layers',
    isPopular: true,
    tags: ['pdf', 'merge', 'combine', 'join', 'documents'],
    privacyNote: '100% on-device processing. Your PDF files are never uploaded to any server.',
    seoTitle: 'PDF Merge Online — Combine Multiple PDFs Free | Less Creation',
    seoDescription: 'Merge PDF files online directly in your browser. Fast, 100% private, zero uploads, unlimited pages.',
    faq: [
      { question: 'Are my PDF files uploaded to your server?', answer: 'No. Less Creation merges your PDFs completely inside your browser using client-side WebAssembly and JavaScript. No document leaves your device.' },
      { question: 'Can I reorder the files before merging?', answer: 'Yes, you can drag or use up/down controls to arrange files in the exact sequence you desire before combining.' }
    ],
    relatedSlugs: ['pdf-split', 'pdf-compress', 'pdf-rotate']
  },
  {
    id: 'tool-pdf-split',
    name: 'PDF Split',
    nameHi: 'पीडीएफ स्प्लिट',
    slug: 'pdf-split',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    categoryLabelHi: 'पीडीएफ टूल्स',
    description: 'Extract specific pages or page ranges from any PDF into a new document.',
    descriptionHi: 'किसी भी पीडीएफ से विशेष पेज या पेज रेंज अलग करें।',
    iconName: 'Scissors',
    isPopular: true,
    tags: ['pdf', 'split', 'extract', 'pages', 'separate'],
    privacyNote: '100% on-device processing. Zero file uploads.',
    seoTitle: 'Split PDF Online — Extract Pages Fast & Free | Less Creation',
    seoDescription: 'Extract pages from PDF online without uploading. Fast, safe, private browser-based PDF splitter.',
    faq: [
      { question: 'How do I specify which pages to extract?', answer: 'You can enter page numbers or ranges like "1-3, 5, 8-10" to extract just those pages.' }
    ],
    relatedSlugs: ['pdf-merge', 'pdf-rotate', 'pdf-page-counter']
  },
  {
    id: 'tool-pdf-compress',
    name: 'PDF Compress',
    nameHi: 'पीडीएफ कंप्रेस',
    slug: 'pdf-compress',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    categoryLabelHi: 'पीडीएफ टूल्स',
    description: 'Reduce the file size of your PDF documents for easier emailing and uploading.',
    descriptionHi: 'ईमेल और अपलोडिंग के लिए अपनी पीडीएफ फाइल का साइज छोटा करें।',
    iconName: 'Minimize2',
    isPopular: true,
    tags: ['pdf', 'compress', 'reduce size', 'optimize', 'shrink'],
    privacyNote: '100% on-device processing. Your documents remain completely private.',
    seoTitle: 'Compress PDF Online — Reduce PDF File Size Free | Less Creation',
    seoDescription: 'Compress PDF files online safely in your browser. Reduce file size without losing readability.',
    relatedSlugs: ['pdf-merge', 'image-compressor']
  },
  {
    id: 'tool-pdf-rotate',
    name: 'PDF Rotate',
    nameHi: 'पीडीएफ रोटेट',
    slug: 'pdf-rotate',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    categoryLabelHi: 'पीडीएफ टूल्स',
    description: 'Rotate sideways or upside-down PDF pages 90, 180, or 270 degrees permanently.',
    descriptionHi: 'उल्टे या आड़े पीडीएफ पेजों को सही दिशा (90°, 180°, 270°) में घुमाएं।',
    iconName: 'RotateCw',
    isPopular: false,
    tags: ['pdf', 'rotate', 'turn', 'orientation', 'pages'],
    privacyNote: '100% client-side. Zero server uploads.',
    seoTitle: 'Rotate PDF Online — Permanently Turn PDF Pages Free | Less Creation',
    seoDescription: 'Rotate PDF pages 90, 180, or 270 degrees in your browser. Save rotated PDF instantly.',
    relatedSlugs: ['pdf-merge', 'pdf-split']
  },
  {
    id: 'tool-images-to-pdf',
    name: 'Images to PDF',
    nameHi: 'इमेज से पीडीएफ',
    slug: 'images-to-pdf',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    categoryLabelHi: 'पीडीएफ टूल्स',
    description: 'Convert multiple JPG, PNG, or WebP images into a single clean PDF document.',
    descriptionHi: 'कई JPG या PNG फोटो को एक स्वच्छ पीडीएफ दस्तावेज में बदलें।',
    iconName: 'FileImage',
    isPopular: true,
    tags: ['images to pdf', 'jpg to pdf', 'png to pdf', 'photos to document'],
    privacyNote: 'Local browser conversion. No images leave your computer or phone.',
    seoTitle: 'Convert Images to PDF Online — JPG & PNG to PDF Free | Less Creation',
    seoDescription: 'Convert JPG, PNG, and WebP images into PDF format instantly in your browser.',
    relatedSlugs: ['pdf-merge', 'image-converter']
  },
  {
    id: 'tool-pdf-metadata',
    name: 'PDF Metadata Viewer',
    nameHi: 'पीडीएफ मेटाडेटा व्यूअर',
    slug: 'pdf-metadata',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    categoryLabelHi: 'पीडीएफ टूल्स',
    description: 'Inspect author, title, creation date, modification date, producer, and page count.',
    descriptionHi: 'पीडीएफ के लेखक, शीर्षक, निर्माण तिथि, पेज संख्या और सॉफ्टवेयर विवरण देखें।',
    iconName: 'FileSearch',
    isPopular: false,
    tags: ['pdf', 'metadata', 'properties', 'author', 'pages'],
    privacyNote: 'Inspected purely on your local machine.',
    seoTitle: 'PDF Metadata Viewer — View PDF Properties Free | Less Creation',
    seoDescription: 'Inspect PDF metadata including author, title, creation date, and page count instantly.',
    relatedSlugs: ['pdf-page-counter', 'pdf-merge']
  },
  {
    id: 'tool-pdf-page-counter',
    name: 'PDF Page Counter',
    nameHi: 'पीडीएफ पेज काउंटर',
    slug: 'pdf-page-counter',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    categoryLabelHi: 'पीडीएफ टूल्स',
    description: 'Quickly count total pages across multiple PDFs without opening each one.',
    descriptionHi: 'बिना हर फाइल खोले एक साथ कई पीडीएफ के कुल पेजों की त्वरित गिनती करें।',
    iconName: 'Hash',
    isPopular: false,
    tags: ['pdf', 'page count', 'counter', 'pages', 'bulk'],
    privacyNote: 'On-device inspection.',
    seoTitle: 'PDF Page Counter — Count Pages in PDF Files Free | Less Creation',
    seoDescription: 'Instantly count the exact number of pages in one or multiple PDF documents.',
    relatedSlugs: ['pdf-metadata', 'pdf-merge']
  },

  // ===================== B. IMAGE TOOLS =====================
  {
    id: 'tool-image-compressor',
    name: 'Image Compressor',
    nameHi: 'इमेज कंप्रेसर',
    slug: 'image-compressor',
    category: 'image',
    categoryLabel: 'Image Tools',
    categoryLabelHi: 'इमेज टूल्स',
    description: 'Compress JPG, PNG, and WebP images to reduce file size with quality control.',
    descriptionHi: 'फोटो की क्वालिटी बनाए रखते हुए उसका साइज (KB/MB) छोटा करें।',
    iconName: 'Minimize2',
    isPopular: true,
    tags: ['image', 'compress', 'reduce kb', 'photo size', 'shrink image'],
    privacyNote: 'Processed locally in HTML5 Canvas. Never uploaded.',
    seoTitle: 'Image Compressor Online — Compress JPG & PNG in KB | Less Creation',
    seoDescription: 'Compress images online with adjustable quality slider. 100% private, instant download.',
    relatedSlugs: ['image-resizer', 'image-converter']
  },
  {
    id: 'tool-image-resizer',
    name: 'Image Resizer',
    nameHi: 'इमेज रिसाइज़र',
    slug: 'image-resizer',
    category: 'image',
    categoryLabel: 'Image Tools',
    categoryLabelHi: 'इमेज टूल्स',
    description: 'Resize images by width and height in pixels, centimeters, or percentage with aspect lock.',
    descriptionHi: 'फोटो की चौड़ाई और ऊंचाई (Pixels, CM या %) अपनी आवश्यकतानुसार बदलें।',
    iconName: 'Maximize2',
    isPopular: true,
    tags: ['image', 'resize', 'dimensions', 'width', 'height', 'scale'],
    privacyNote: 'Resized inside your browser canvas.',
    seoTitle: 'Image Resizer Online — Resize Photo Dimensions Free | Less Creation',
    seoDescription: 'Resize photos and pictures to exact pixel dimensions or percentage without blur.',
    relatedSlugs: ['image-compressor', 'image-crop']
  },
  {
    id: 'tool-image-crop',
    name: 'Image Crop & Aspect',
    nameHi: 'इमेज क्रॉप',
    slug: 'image-crop',
    category: 'image',
    categoryLabel: 'Image Tools',
    categoryLabelHi: 'इमेज टूल्स',
    description: 'Crop images to 1:1 square, 4:3, 16:9 widescreen, or custom proportions.',
    descriptionHi: 'तस्वीर को 1:1 स्क्वायर, 4:3, 16:9 या मनचाहे अनुपात में क्रॉप करें।',
    iconName: 'Crop',
    isPopular: false,
    tags: ['crop', 'cut', 'aspect ratio', 'square', 'avatar'],
    privacyNote: 'Direct browser crop.',
    seoTitle: 'Crop Image Online — Easy Square & Custom Photo Cropper | Less Creation',
    seoDescription: 'Crop images quickly with preset aspect ratios (1:1, 16:9, 4:3) or freeform selection.',
    relatedSlugs: ['image-resizer', 'image-compressor']
  },
  {
    id: 'tool-image-converter',
    name: 'Image Format Converter',
    nameHi: 'इमेज फॉर्मेट कनवर्टर',
    slug: 'image-converter',
    category: 'image',
    categoryLabel: 'Image Tools',
    categoryLabelHi: 'इमेज टूल्स',
    description: 'Convert between JPG, PNG, and WebP formats instantly with high fidelity.',
    descriptionHi: 'JPG, PNG और WebP फॉर्मेट के बीच तुरंत और आसानी से फोटो बदलें।',
    iconName: 'RefreshCw',
    isPopular: true,
    tags: ['convert', 'jpg to png', 'png to jpg', 'webp converter', 'photo format'],
    privacyNote: '100% on-device canvas rendering.',
    seoTitle: 'Image Converter — JPG to PNG, PNG to JPG, WebP Free | Less Creation',
    seoDescription: 'Convert image files between JPG, PNG, and WebP formats with zero loss in quality.',
    relatedSlugs: ['images-to-pdf', 'image-compressor']
  },
  {
    id: 'tool-image-dimension-calc',
    name: 'Image Dimension & DPI Calculator',
    nameHi: 'इमेज डाइमेंशन और डीपीआई कैलकुलेटर',
    slug: 'image-dimension-calc',
    category: 'image',
    categoryLabel: 'Image Tools',
    categoryLabelHi: 'इमेज टूल्स',
    description: 'Calculate print dimensions, aspect ratio, Megapixels, and resolution (DPI/PPI).',
    descriptionHi: 'फोटो का प्रिंट साइज, आस्पेक्ट रेशियो, मेगापिक्सल और डीपीआई कैलकुलेट करें।',
    iconName: 'Sliders',
    isPopular: false,
    tags: ['dpi', 'ppi', 'aspect ratio', 'megapixels', 'print size', 'resolution'],
    privacyNote: 'Pure mathematical calculation on device.',
    seoTitle: 'Image Dimension & Aspect Ratio Calculator | Less Creation',
    seoDescription: 'Calculate aspect ratio, print size in inches/cm, and megapixel count for any resolution.',
    relatedSlugs: ['image-resizer', 'unit-converter']
  },

  // ===================== C. TEXT TOOLS =====================
  {
    id: 'tool-word-counter',
    name: 'Word & Character Counter',
    nameHi: 'शब्द एवं अक्षर काउंटर',
    slug: 'word-counter',
    category: 'text',
    categoryLabel: 'Text Tools',
    categoryLabelHi: 'टेक्स्ट टूल्स',
    description: 'Count words, characters (with & without spaces), lines, sentences, and estimated reading time.',
    descriptionHi: 'शब्द, कुल अक्षर, लाइनें, वाक्य और पढ़ने में लगने वाले समय की सटीक गणना करें।',
    iconName: 'Type',
    isPopular: true,
    tags: ['word counter', 'character count', 'reading time', 'text analysis'],
    privacyNote: 'Your text is never sent to any server.',
    seoTitle: 'Word Counter & Character Counter Online | Less Creation',
    seoDescription: 'Count words, characters, sentences, paragraphs, and reading time in real-time.',
    relatedSlugs: ['case-converter', 'text-cleaner']
  },
  {
    id: 'tool-case-converter',
    name: 'Text Case Converter',
    nameHi: 'टेक्स्ट केस कनवर्टर',
    slug: 'case-converter',
    category: 'text',
    categoryLabel: 'Text Tools',
    categoryLabelHi: 'टेक्स्ट टूल्स',
    description: 'Transform text to UPPERCASE, lowercase, Title Case, Sentence case, camelCase, or snake_case.',
    descriptionHi: 'टेक्स्ट को अपरकेस, लोअरकेस, टाइटल केस या सेंटेंस केस में तुरंत बदलें।',
    iconName: 'ArrowUpDown',
    isPopular: true,
    tags: ['case converter', 'uppercase', 'lowercase', 'title case', 'capitalize'],
    privacyNote: 'Local JavaScript transformation.',
    seoTitle: 'Case Converter — Convert UPPERCASE, lowercase, Title Case | Less Creation',
    seoDescription: 'Change text capitalization effortlessly to Title Case, Sentence case, UPPERCASE, and camelCase.',
    relatedSlugs: ['word-counter', 'text-cleaner']
  },
  {
    id: 'tool-text-cleaner',
    name: 'Text Cleaner & Space Remover',
    nameHi: 'टेक्स्ट क्लीनर एवं स्पेस रिमूवर',
    slug: 'text-cleaner',
    category: 'text',
    categoryLabel: 'Text Tools',
    categoryLabelHi: 'टेक्स्ट टूल्स',
    description: 'Remove double spaces, trailing whitespaces, blank lines, and unwanted punctuation.',
    descriptionHi: 'अनावश्यक अतिरिक्त स्पेस, खाली लाइनें और फालतू विराम चिह्न हटाएं।',
    iconName: 'Sparkles',
    isPopular: false,
    tags: ['clean text', 'remove spaces', 'strip whitespace', 'empty lines'],
    privacyNote: 'Processed entirely in client memory.',
    seoTitle: 'Remove Extra Spaces & Clean Text Online | Less Creation',
    seoDescription: 'Clean up copied text by removing excess spaces, double spaces, and blank lines instantly.',
    relatedSlugs: ['duplicate-line-remover', 'word-counter']
  },
  {
    id: 'tool-duplicate-line-remover',
    name: 'Duplicate Line Remover & Sorter',
    nameHi: 'डुप्लिकेट लाइन रिमूवर एवं सॉर्टर',
    slug: 'duplicate-line-remover',
    category: 'text',
    categoryLabel: 'Text Tools',
    categoryLabelHi: 'टेक्स्ट टूल्स',
    description: 'Deduplicate text lines, sort alphabetically (A-Z or Z-A), and remove empty lines.',
    descriptionHi: 'दोहराई गई पंक्तियाँ (डुप्लिकेट लाइनें) हटाएं और वर्णमाला क्रम में व्यवस्थित करें।',
    iconName: 'ListFilter',
    isPopular: false,
    tags: ['duplicates', 'unique lines', 'sort text', 'alphabetize', 'list'],
    privacyNote: 'Processed locally in browser.',
    seoTitle: 'Duplicate Line Remover & Text Sorter Online | Less Creation',
    seoDescription: 'Remove duplicate lines from lists and sort text alphabetically or reverse with one click.',
    relatedSlugs: ['text-cleaner', 'word-counter']
  },
  {
    id: 'tool-find-and-replace',
    name: 'Find and Replace Text',
    nameHi: 'खोजें और बदलें (Find & Replace)',
    slug: 'find-and-replace',
    category: 'text',
    categoryLabel: 'Text Tools',
    categoryLabelHi: 'टेक्स्ट टूल्स',
    description: 'Find words or phrases in large texts and replace them with match count and case-sensitivity.',
    descriptionHi: 'बड़े लेखों में शब्द या वाक्य खोजें और उन्हें आसानी से नए शब्दों से बदलें।',
    iconName: 'Search',
    isPopular: false,
    tags: ['find and replace', 'search text', 'replace words', 'substitute'],
    privacyNote: '100% private in-browser tool.',
    seoTitle: 'Find and Replace Text Online — Batch Word Replacement | Less Creation',
    seoDescription: 'Quickly find and replace words, characters, and phrases in your text with real-time match counter.',
    relatedSlugs: ['case-converter', 'text-diff']
  },
  {
    id: 'tool-text-diff',
    name: 'Text Comparison & Diff',
    nameHi: 'टेक्स्ट तुलना एवं अंतर (Diff)',
    slug: 'text-diff',
    category: 'text',
    categoryLabel: 'Text Tools',
    categoryLabelHi: 'टेक्स्ट टूल्स',
    description: 'Compare two versions of text side-by-side to highlight added, removed, or changed words.',
    descriptionHi: 'दो अलग-अलग लेखों या ड्राफ्ट की तुलना करें और बदलावों को स्पष्ट रूप से देखें।',
    iconName: 'GitCompare',
    isPopular: false,
    tags: ['diff', 'compare text', 'text difference', 'revision', 'changes'],
    privacyNote: 'Zero server communication.',
    seoTitle: 'Text Difference Checker — Compare Two Texts Online | Less Creation',
    seoDescription: 'Compare two text snippets or documents side-by-side to detect additions and deletions.',
    relatedSlugs: ['find-and-replace', 'word-counter']
  },

  // ===================== D. CALCULATORS =====================
  {
    id: 'tool-percentage-calculator',
    name: 'Percentage Calculator',
    nameHi: 'प्रतिशत कैलकुलेटर',
    slug: 'percentage-calculator',
    category: 'calculators',
    categoryLabel: 'Calculators',
    categoryLabelHi: 'कैलकुलेटर',
    description: 'Calculate percentages, percentage increase/decrease, fractions to percentage, and discounts.',
    descriptionHi: 'प्रतिशत निकालें, प्रतिशत वृद्धि/कमी और छूट की त्वरित गणना करें।',
    iconName: 'Percent',
    isPopular: true,
    tags: ['percentage', 'percent', 'math', 'increase', 'decrease', 'fraction'],
    privacyNote: 'Pure on-device math.',
    seoTitle: 'Percentage Calculator Online — Calculate %, Increase & Decrease | Less Creation',
    seoDescription: 'Free online percentage calculator. Find percentage of a number, percentage change, and differences.',
    relatedSlugs: ['discount-calculator', 'gst-calculator']
  },
  {
    id: 'tool-age-calculator',
    name: 'Age & Date Difference Calculator',
    nameHi: 'आयु एवं तिथि अंतर कैलकुलेटर',
    slug: 'age-calculator',
    category: 'calculators',
    categoryLabel: 'Calculators',
    categoryLabelHi: 'कैलकुलेटर',
    description: 'Calculate your exact age in years, months, days, hours, and next birthday countdown.',
    descriptionHi: 'वर्ष, महीने, दिन और घंटों में अपनी सटीक आयु और अगले जन्मदिन का समय जानें।',
    iconName: 'Calendar',
    isPopular: true,
    tags: ['age', 'birthday', 'date difference', 'chronological age', 'calculator'],
    privacyNote: 'Direct browser calculation.',
    seoTitle: 'Age Calculator Online — Calculate Exact Age in Years, Months, Days | Less Creation',
    seoDescription: 'Find your exact age down to the day and see days remaining until your next birthday.',
    relatedSlugs: ['date-difference', 'legal-limitation-calculator']
  },
  {
    id: 'tool-date-difference',
    name: 'Date Difference Calculator',
    nameHi: 'दो तिथियों के बीच अंतर',
    slug: 'date-difference',
    category: 'calculators',
    categoryLabel: 'Calculators',
    categoryLabelHi: 'कैलकुलेटर',
    description: 'Calculate days, weeks, months, or working business days between any two dates.',
    descriptionHi: 'किन्हीं भी दो तारीखों के बीच कुल दिन, सप्ताह, महीने या कार्यदिवस निकालें।',
    iconName: 'Clock',
    isPopular: false,
    tags: ['date difference', 'days between dates', 'duration', 'calendar math'],
    privacyNote: 'Instant browser math.',
    seoTitle: 'Date Difference Calculator — Days Between Two Dates | Less Creation',
    seoDescription: 'Calculate the duration and exact number of days, weeks, and months between two dates.',
    relatedSlugs: ['age-calculator', 'legal-limitation-calculator']
  },
  {
    id: 'tool-emi-calculator',
    name: 'Loan & EMI Calculator',
    nameHi: 'लोन एवं ईएमआई कैलकुलेटर',
    slug: 'emi-calculator',
    category: 'calculators',
    categoryLabel: 'Calculators',
    categoryLabelHi: 'कैलकुलेटर',
    description: 'Calculate monthly EMI, total interest payable, and total loan payment for home, car, or personal loans.',
    descriptionHi: 'होम, कार या पर्सनल लोन के लिए मासिक ईएमआई और कुल ब्याज की गणना करें।',
    iconName: 'CreditCard',
    isPopular: true,
    tags: ['emi', 'loan', 'interest', 'monthly payment', 'finance'],
    privacyNote: 'Safe mathematical formulas executed on device.',
    seoTitle: 'EMI Calculator Online — Home Loan & Personal Loan EMI | Less Creation',
    seoDescription: 'Calculate monthly EMI and total interest for home, car, and personal loans with interactive sliders.',
    relatedSlugs: ['gst-calculator', 'percentage-calculator']
  },
  {
    id: 'tool-gst-calculator',
    name: 'GST Calculator (India)',
    nameHi: 'जीएसटी कैलकुलेटर (भारत)',
    slug: 'gst-calculator',
    category: 'calculators',
    categoryLabel: 'Calculators',
    categoryLabelHi: 'कैलकुलेटर',
    description: 'Calculate GST inclusive and exclusive amounts across standard tax slabs (5%, 12%, 18%, 28%).',
    descriptionHi: '5%, 12%, 18% और 28% स्लैब के आधार पर जीएसटी राशि जोड़ें या निकालें।',
    iconName: 'Receipt',
    isPopular: true,
    tags: ['gst', 'tax', 'cgst', 'sgst', 'invoice calculation', 'india'],
    privacyNote: 'Executed directly in browser.',
    seoTitle: 'GST Calculator India — Calculate GST Inclusive & Exclusive | Less Creation',
    seoDescription: 'Quickly calculate GST inclusive and exclusive prices with CGST and SGST bifurcation for Indian tax slabs.',
    relatedSlugs: ['discount-calculator', 'emi-calculator']
  },
  {
    id: 'tool-discount-calculator',
    name: 'Discount & Margin Calculator',
    nameHi: 'छूट एवं डिस्काउंट कैलकुलेटर',
    slug: 'discount-calculator',
    category: 'calculators',
    categoryLabel: 'Calculators',
    categoryLabelHi: 'कैलकुलेटर',
    description: 'Calculate discounted price, total savings, and profit margins for shopping and sales.',
    descriptionHi: 'छूट के बाद अंतिम कीमत, कुल बचत और मुनाफे के मार्जिन की गणना करें।',
    iconName: 'Tag',
    isPopular: false,
    tags: ['discount', 'sale', 'savings', 'percentage off', 'price'],
    privacyNote: 'Pure on-device arithmetic.',
    seoTitle: 'Discount Calculator — Calculate Sale Price and Savings | Less Creation',
    seoDescription: 'Calculate discounted item prices, money saved, and multiple stacked discounts easily.',
    relatedSlugs: ['percentage-calculator', 'gst-calculator']
  },
  {
    id: 'tool-unit-converter',
    name: 'Universal Unit Converter',
    nameHi: 'यूनिवर्सल यूनिट कनवर्टर',
    slug: 'unit-converter',
    category: 'calculators',
    categoryLabel: 'Calculators',
    categoryLabelHi: 'कैलकुलेटर',
    description: 'Convert Length, Weight, Area (including Bigha, Acre, Guntha), Temperature, and Volume.',
    descriptionHi: 'लंबाई, वजन, क्षेत्रफल (बीघा, एकड़, गुंठा), तापमान और आयतन इकाइयों को बदलें।',
    iconName: 'Compass',
    isPopular: true,
    tags: ['unit converter', 'bigha to acre', 'length', 'weight', 'celsius to fahrenheit'],
    privacyNote: 'Instant client-side calculation.',
    seoTitle: 'Universal Unit Converter — Length, Weight, Area & Land Units | Less Creation',
    seoDescription: 'Convert between metric, imperial, and traditional Indian land measurement units (Acre, Bigha, Hectare).',
    relatedSlugs: ['percentage-calculator', 'image-dimension-calc']
  },

  // ===================== E. QR & DIGITAL TOOLS =====================
  {
    id: 'tool-qr-generator',
    name: 'QR Code Generator',
    nameHi: 'क्यूआर कोड जनरेटर',
    slug: 'qr-generator',
    category: 'qr-digital',
    categoryLabel: 'QR & Digital',
    categoryLabelHi: 'क्यूआर और डिजिटल',
    description: 'Generate high-resolution QR codes for Website URLs, Plain Text, Wi-Fi passwords, vCards, and UPI payments.',
    descriptionHi: 'वेबसाइट यूआरएल, टेक्स्ट, वाई-फाई पासवर्ड, संपर्क और यूपीआई भुगतान के लिए क्यूआर कोड बनाएं।',
    iconName: 'QrCode',
    isPopular: true,
    tags: ['qr code', 'qr generator', 'upi qr', 'wifi qr', 'vcard'],
    privacyNote: 'Generated 100% locally in browser. No data saved.',
    seoTitle: 'QR Code Generator Free — Create URL, WiFi, UPI & Text QR | Less Creation',
    seoDescription: 'Generate crisp, downloadable PNG QR codes for websites, Wi-Fi networks, contacts, and UPI payments.',
    relatedSlugs: ['qr-scanner', 'url-encoder']
  },
  {
    id: 'tool-qr-scanner',
    name: 'QR Code Scanner & Reader',
    nameHi: 'क्यूआर कोड स्कैनर',
    slug: 'qr-scanner',
    category: 'qr-digital',
    categoryLabel: 'QR & Digital',
    categoryLabelHi: 'क्यूआर और डिजिटल',
    description: 'Scan and decode QR codes from image files or your device camera in real-time.',
    descriptionHi: 'इमेज फाइल अपलोड करके या डिवाइस कैमरे से तुरंत क्यूआर कोड स्कैन करें।',
    iconName: 'Scan',
    isPopular: false,
    tags: ['qr scanner', 'read qr', 'decode qr', 'camera scan'],
    privacyNote: 'Camera stream and images are processed strictly on-device.',
    seoTitle: 'QR Code Scanner Online — Read QR from Image or Camera | Less Creation',
    seoDescription: 'Scan and read QR codes from uploaded images or camera with instant text decoding.',
    relatedSlugs: ['qr-generator', 'url-encoder']
  },
  {
    id: 'tool-password-generator',
    name: 'Secure Password Generator',
    nameHi: 'सुरक्षित पासवर्ड जनरेटर',
    slug: 'password-generator',
    category: 'qr-digital',
    categoryLabel: 'QR & Digital',
    categoryLabelHi: 'क्यूआर और डिजिटल',
    description: 'Generate strong, uncrackable cryptographic passwords with customizable symbols, numbers, and strength meter.',
    descriptionHi: 'प्रतीकों, संख्याओं और शक्ति मापक के साथ मजबूत व सुरक्षित पासवर्ड बनाएं।',
    iconName: 'Key',
    isPopular: true,
    tags: ['password generator', 'strong password', 'security', 'crypto random'],
    privacyNote: 'Generated via window.crypto.getRandomValues. Never transmitted.',
    seoTitle: 'Strong Password Generator Online — Cryptographically Secure | Less Creation',
    seoDescription: 'Generate strong, randomized passwords with uppercase, lowercase, numbers, and symbols securely.',
    relatedSlugs: ['base64-converter', 'qr-generator']
  },

  // ===================== F. PRODUCTIVITY TOOLS =====================
  {
    id: 'tool-random-picker',
    name: 'Random Item & Number Picker',
    nameHi: 'रैंडम पिकर एवं व्हील',
    slug: 'random-picker',
    category: 'productivity',
    categoryLabel: 'Productivity',
    categoryLabelHi: 'उत्पादकता',
    description: 'Pick random items from a list, roll dice, or generate random numbers for unbiased decision making.',
    descriptionHi: 'लिस्ट में से यादृच्छिक नाम चुनें, पासा फेंकें या निष्पक्ष निर्णय के लिए नंबर निकालें।',
    iconName: 'Shuffle',
    isPopular: false,
    tags: ['random picker', 'decision maker', 'random number', 'list picker', 'dice'],
    privacyNote: 'Calculated using browser cryptographic RNG.',
    seoTitle: 'Random Picker Online — Unbiased Decision & List Picker | Less Creation',
    seoDescription: 'Pick a random winner, item from your list, or generate random numbers in an instant.',
    relatedSlugs: ['password-generator', 'focus-timer']
  },


];

export const TOTAL_TOOLS_COUNT = TOOLS_REGISTRY.length;

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS_REGISTRY.find(t => t.slug === slug);
}

export const POPULAR_TOOLS = TOOLS_REGISTRY.filter(t => t.isPopular);

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return TOOLS_REGISTRY.filter(t => t.category === category);
}

export function searchTools(query: string): ToolDefinition[] {
  const clean = query.trim().toLowerCase();
  if (!clean) return TOOLS_REGISTRY;

  return TOOLS_REGISTRY.filter(tool => {
    return (
      tool.name.toLowerCase().includes(clean) ||
      (tool.nameHi && tool.nameHi.includes(clean)) ||
      tool.description.toLowerCase().includes(clean) ||
      tool.category.toLowerCase().includes(clean) ||
      tool.categoryLabel.toLowerCase().includes(clean) ||
      tool.tags.some(tag => tag.toLowerCase().includes(clean))
    );
  });
}
